# Вкл/выкл автоматичесский запуск сканирования при переходе на страницу скрипта
on: false

# Кодровка cайта
# Задаётся для отправки писем
charset: 'utf-8'

# Название сайта
# Будет указано в качестве имени автора письма
sitename: 'Сообщение AntiShell: "на сайте '

# Начальный путь проверки. '' - корень сайта
# Для сканирования отдельной папки: '/folderName'
path: ''

# Куда сохранять результат скана системы.
# Путь от корня сайта.
scanfile: 'system/assests/log/anti-shell.log'

# Создавать НОВЫЙ снимок сразу по окочании сканирования
# Для отключения необходимо заменить на false
# Для ручного создания снимка при отключенном автоматическом создании нужно запустить скрипт
# с параметром snap=y (http:site.com/antishell.php?snap=y)
allowsnap: false

# Список расширений файлов, которые необходимо проверять.
# '' - означает любые расширения. Расширения указывать без точек через запятую
# Например, 'php,cgi,pl,perl,php3,php4,php5,php6,tpl,js,htaccess,htm,html,css,swf,txt,db,lng',
ext: ''

# Список расширений файлов, которые не надо учитывать при проверке. Расширения указывать без точек через запятую
# А также можно указывать имена файлов, которые тоже не надо учитывать.
# Например, 'skipfile: 'index.php,jpg', - здесь не будут учитываться файлы с именами 'index.php' и
# все файлы с расширением JPG
# В этот список автоматически добавляется файл снимка.
skipfile: 'jpg,jpeg,gif,bmp,png,rar,zip,tmp,gz,xml,flv,exe,txt,doc,pdf,avi,mp3,mp4,wmv,m4v,m4a,mov,3gp,f4v,3gp,mpg,mpeg'

# Список папок, которые не надо проверять. Путь указывается относительно значения переменной 'path'.
# Перечилять папки через запятую
# Например, 'skipdir: '/folder,/files/web'
skipdir: '/system/assests,/.git,/.idea'

# Email, на который отправлять отчеты
# Можно указывать несколько адресов через запятую, на каждый адрес будет выслано отдельное письмо
email: 'alexjurii@gmail.com'

# Email отправителя
# Если не задан - будет взят из предыдущего параметра
from_email: 'robot@alexshop.cms'

# Отображать на экране статистику проверки? На почту в любом случае будет отправляться.
show_text: true

# Путь к файлу с картинками-индикаторами
# Можно скопировать файл себе на хостинг и вставить сылку на него сюда.
icon_url: '/backend/design/images/as_sprite.png'
