allow_attach: '1'
formats: 'jpg,zip,rar'
file_size: '10000000'
keywords: 'обратная связь, контакты, feedback, связь с администрацией'
description: 'Обратная связь, место где вы можете связаться с администрацией сайта!'
