dropbox:
    prefix.dir: ''
    access.token: VpKgIdfD4ZMAAAAAAACLlumDQQ5RJBfyu6ufHYEtcDOnwagdrDwP2QfyMhuZ97rL
    app.secret: ewc69x9phcxrskm
    app.key: vs17e81nvxecjjd
ftp:
    host: ftp.example.com
    username: username
    password: password
    port: 21
    root: /path/to/root
    passive: true
    ssl: true
    timeout: 30
