size-mini: '150'
size-long: '450'
alb-col: '3'
photos-col: '3'
photos-num: '8'
search-col: '3'
search-num: '8'
comment: '1'
add: '1'
save: files/gallery/
save-thumb: files/gallery/thumb/
waterdir: files/gallery/watermark.png
quality: '100'
max_size: '1048578'
typefile: 'jpg,jpeg,gif,png,bmp'
