# все доступные разрешения для usera
- products
- comment
- comment_edit
- categories
- brands
- features
- orders
- labels
- users
- groups
- coupons
- pages
- blog
- comments
- feedbacks
- import
- export
- stats
- design
- settings
- settings2
- currency
- delivery
- payment
- managers
- license
- languages
- banners
- special
- callbacks
- topvisor
- yametrika
- robots
- service
- antivirus
- soon
- dump
