ProductsAdmin: 'products'
ProductAdmin: 'products'
CategoriesAdmin: 'categories'
CategoryAdmin: 'categories'
BrandsAdmin: 'brands'
BrandAdmin: 'brands'
FeaturesAdmin: 'features'
FeatureAdmin: 'features'
OrdersAdmin: 'orders'
OrderAdmin: 'orders'
OrdersLabelsAdmin: 'labels'
OrdersLabelAdmin: 'labels'
UsersAdmin: 'users'
UserAdmin: 'users'
ExportUsersAdmin: 'users'
GroupsAdmin: 'groups'
GroupAdmin: 'groups'
CouponsAdmin: 'coupons'
CouponAdmin: 'coupons'
PagesAdmin: 'pages'
PageAdmin: 'pages'
BlogAdmin: 'blog'
PostAdmin: 'blog'
CommentsAdmin: 'comments'
FeedbacksAdmin: 'feedbacks'
ImportAdmin: 'import'
ExportAdmin: 'export'
MultiImportAdmin: 'import'
MultiExportAdmin: 'export'
StatsAdmin: 'stats'
ThemeAdmin: 'design'
StylesAdmin: 'design'
TemplatesAdmin: 'design'
ImagesAdmin: 'design'
ScriptsAdmin: 'design'
SettingsAdmin: 'settings'
CurrencyAdmin: 'currency'
DeliveriesAdmin: 'delivery'
DeliveryAdmin: 'delivery'
PaymentMethodAdmin: 'payment'
PaymentMethodsAdmin: 'payment'
ManagersAdmin: 'managers'
ManagerAdmin: 'managers'
LicenseAdmin: 'license'
SubscribeMailingAdmin: 'users'
BannersAdmin: 'banners'
BannerAdmin: 'banners'
BannersImagesAdmin: 'banners'
BannersImageAdmin: 'banners'
SpecialAdmin: 'special'
CallbacksAdmin: 'callbacks'

CommentAdmin: 'comment'
CommentEditAdmin: 'comment_edit'

# Мультиязычность start
LanguageAdmin: 'languages'
LanguagesAdmin: 'languages'
TranslationAdmin: 'languages'
TranslationsAdmin: 'languages'
JqGridAjaxTranslations: 'languages'
# Мультиязычность end
#statistic*/
ReportStatsAdmin: 'stats'
CategoryStatsAdmin: 'stats'
#statistic*/
TopvisorProjectsAdmin: 'topvisor'
TopvisorProjectAdmin: 'topvisor'
#YaMetrika*/
YametrikaAdmin: 'yametrika'
#YaMetrika*/
RobotsAdmin: 'robots'
ComingSoon: 'soon'
#Service - Обслуживание сайта
ServiceAdmin: 'service'
MySqlDumper: 'dump'
AntiShell: 'antivirus'
