num: '5'
comments_num: '10'
fullLink: '0'
noModer: '1'
preModer: '20'
related_news: '10'
addNews: '1'
showCat: '1'
subLoad: '1'
catCols: '3'
showBreadcumb: '1'
tags: '1'
tags_num: '3'
tagIll: '0'
illFormat: '<b>{tag}</b>'
limitStar: '5'
starStyle: ''
carma_rate: '0'
carma_summ: '0'
fileEditor: '1'
imgFormats: 'jpg,gif,png'
attachFormats: 'zip,rar,mp3,avi,mp4,flv,3gp,torrent'
max_size: '1024000000000000000'
thumb_width: '600'
