error_reporting: '-1'
php_charset: 'UTF8'
php_locale_collate: 'ru_RU'
php_locale_ctype: 'ru_RU'
php_locale_monetary: 'ru_RU'
php_locale_numeric: 'ru_RU'
php_locale_time: 'ru_RU'
#php_timezone: 'Europe/Moscow'