version_id: 1.0.0
active-stat: '1'
admin-stat: '0'
txt-stat: '1'
img-stat: '0'
img_path: /media/comments
comm-num-0: '0'
comm-num-1: '5'
comm-num-2: '30'
comm-num-3: '50'
comm-num-4: '75'
comm-num-5: '150'
comm-num-6: '300'
comm-num-7: '450'
comm-num-8: '600'
comm-num-9: '700'
comm-num-10: '800'
comm-num-11: '900'
comm-num-12: '1100'
comm-num-13: '1300'
comm-num-14: '1500'
comm-num-15: '1700'
comm-num-16: '1900'
comm-num-17: '2100'
comm-num-18: '2500'
comm-num-19: '3000'
guests: Прохожий
text-stat-0: Новичок
text-stat-1: 'Иногда посещаю'
text-stat-2: 'Частый гость'
text-stat-3: Любознательный
text-stat-4: 'Младший Комментатор'
text-stat-5: Комментатор
text-stat-6: Общительный
text-stat-7: Супер-общительный
text-stat-8: 'Младший активист'
text-stat-9: Активист
text-stat-10: Супер-активист
text-stat-11: 'Лучший собеседник'
text-stat-12: 'Душа компании'
text-stat-13: 'Заслуженный пользователь'
text-stat-14: Авторитет
text-stat-15: Маэстро
text-stat-16: 'Постоялец сайта'
text-stat-17: 'Местный житель'
text-stat-18: 'Легенда сайта'
color-0: '#999900'
color-1: '#CC9900'
color-2: '#CC6600'
color-3: '#993300'
color-4: '#660066'
color-5: '#3300CC'
color-6: '#009933'
color-7: '#008080'
color-8: '#336600'
color-9: '#800000'
color-10: '#660066'
color-11: '#3300CC'
color-12: '#009933'
color-13: '#008080'
color-14: '#336600'
color-15: '#800000'
color-16: '#660066'
color-17: '#3300CC'
color-18: '#CC0000'
remain_user: 'до следующего звания Вам '
remain_admin: 'администратор '
remain_moder: 'модератор '
remain_guests: 'гости не участвуют в рейтинге '
active: 'На сайте'
no_active: 'Нет на сайте'
