xNums: '278019'
stopNick: '%laed*'
stopMails: ''
stopWords: 'хуй,пизда,шлюха,ебан,блядь,ебать,ебал,курва,бляди,пидар'
stopReplace: '*Цензор*'
allowHTML: 'b,i,s,u,font,color'
banIp: "192.15.*.%\r\n127.1.*.*\r\n23.2332.2323.3"
banIpMessage: 'Ваш ip-адрес находится в черном списке!'
switch_cp: '0'
recaptcha: '0'
recaptcha_public: ''
recaptcha_private: ''
captcha_width: '120'
captcha_height: '60'
captcha_lenght: '6'
