switch: '1'
pass: '0'
admin: '0'
vk_is: '1'
vk_client_id: ''
vk_client_secret: ''
ok_is: '1'
ok_client_id: ''
ok_client_secret: ''
ok_public_key: ''
fb_is: '1'
fb_client_id: ''
fb_client_secret: ''
gg_is: '1'
gg_client_id: ''
gg_client_secret: ''
ya_is: '1'
ya_client_id: ''
ya_client_secret: ''
mm_is: '1'
mm_client_id: ''
mm_client_secret: ''
