guestGroup: '3'
botGroup: '4'
banGroup: '5'
count_points: '1'
noAvatar: files/avatars/no_avatar.png
avatar_load: '1'
avatar_width: '100'
avatar_height: '100'
avatar_size: '204800'
with_activate: '1'
activeFlash: '1'
activeVideo: '1'
activeAudio: '1'
activeAttach: '1'
editor: bb
bbViz: '1'
highlightCode: '1'
commentOften: '10'
commentEditText: '[color=green]Сообщение отредактировано {user}, {date}[/color]'
commentSignature: '<noindex><div class=\"signature\">[sig]</div></noindex>'
commentSubscribe: '1'
commentModeration: '1'
commentTree: '1'
pmShown: '1'
isBan: '1'
userWall: '1'
userWallNum: '10'
userFriends: '1'
userGuests: '1'
readBlog: '1'
